### PR TITLE
Update 01_intro.ipynb - IMDb reviews sentiment analysis prediction output change

### PR DESCRIPTION
**Pull request by ShubhamThakkar**
I think output in the markdown cell does not match the description below it.

### CODE REVIEW

**Comment by djsamseng** [comment]
LGTM! This undoes this incorrect change https://github.com/fastai/fastbook/commit/bb0dadf1ec360b957a6ba512da952aef6b69091e#diff-2797ef6b1a7e774fb61038401a8b5d7a9da91f43da3744f3ed6dc18796126074R2265

**Comment by djsamseng** [comment]
> @djsamseng, thanks for reviewing it. Will you be merging it or should we ping someone else?

Yeah ping one of the owners as I don't have merge privileges

**Comment by ShubhamThakkar** [comment]
@jph00 , can you please review it.

**Comment by Anhilina** [comment]
Thanks, Samuel — we reached out to an owner, and the PR has now been merged.

**Pull request merged**
