### PR TITLE
copy edit

### PR DESCRIPTION
**Pull request by pfcrowe**
minor corrections ch2, 3, 4

### CODE REVIEW

**Comment by pfcrowe** [comment]
great chapter! ch3 minor corrections.

question 4 re VW scandal not referenced in chapter body.

'Key examples for data ethics', then 'Topics in data ethics' subheadings both have bullet points, some redundancy, maybe need to refer back to 'key examples' more explicitly or mention that you are now treating each of earlier three topics in detail, and additionally the topic of disinformation.

**Comment by bradsaracik** [comment]
Re q4 VW: "It was one of the engineers, James Liang, who just did what he was told."

**Comment by pfcrowe** [comment]
> It was one of the engineers, James Liang,

🙈🎯 Thanks Brad, oops!

**Comment by jph00** [comment]
Thanks @pfcrowe  - took me a while to get to this due to covid-19 distractions. Could you resolve the conflicts please?

**Comment by pfcrowe** [comment]
np @jph00 done.

good to see the covid work making an impact

**Comment by jph00** [comment]
Merged manually.

**Pull request closed without merging**
